job_deploy_fr:
  environment: production
  variables:
    CI_BUILD_REF_NAME: master
  only:
    - master
  stage: deploy
  tags:
  - fr.atc
  script:
  - GIT_WORK_TREE=/home/blast/public/www/ git checkout -f
  - sleep 10
  - sudo systemctl restart t6ss
  - sudo systemctl restart caddy
job_deploy_us:
  environment: production
  variables:
    CI_BUILD_REF_NAME: master
  only:
    - master
  stage: deploy
  tags:
  - us.atc
  script:
  - GIT_WORK_TREE=/home/blast/public/www/ git checkout -f
  - sleep 10
  - sudo systemctl restart t6ss
  - sudo systemctl restart caddy
job_deploy_dev:
  environment: dev
  variables:
    CI_BUILD_REF_NAME: dev-v2
  only:
    - dev-v2
  stage: deploy
  tags:
  - us.atc.dev
  script:
    - GIT_WORK_TREE=/home/blast/dev/www/ git checkout -f
    - sleep 2
    - sudo systemctl restart t6ss-dev
    - sudo systemctl restart caddy-dev
    
