CLUSTAL W (1.81) multiple sequence alignment

fig|666.1893.peg.1367      MPTPCYIKIEGQTQGLITAGACTADSIGDSFVEGHEDEMLVQQFDHTVTVPTDPQSGQPS
666.1906.peg.1334          ------------------------------------------------------------
fig|666.1899.peg.554       ------------------------------------------------------------
666.1897.peg.2311          MPTPCYISIEGQTQGLITAGACTADSIGDSFVEGHEDEMLVQQFDHVVTVPTDPQSGQPS
666.1907.peg.3336          MPTPCYISIEGQTQGLITAGACTADSIGDSFVEGHEDEMLVQQFDHVVTVPTDPQSGQPS
666.1905.peg.2607          MPTPCYISIEGQTQGLITAGACTADSIGDSFVEGHEDEMLVQQFDHVVTVPTDPQSGQPS
666.1901.peg.1846          MPTPCYISIEGQTQGLITAGACTADSIGDSFVEGHEDEMLVQQFDHVVTVPTDPQSGQPS
hcp2                       MPTPCYISIEGQTQGLITAGACTADSIGDSFVEGHEDEMLVQQFDHVVTVPTDPQSGQPS
                                                                                       

fig|666.1893.peg.1367      GQRVHKPFKFTVALNKAVPLLYNALSSGEKLKSVELKWYRTSLEGKQENFFTTKLENASI
666.1906.peg.1334          -----------MALNKAVPLLYNALSSGEKLKTVELKWYRTSIEGKQENFFTTKLENASI
fig|666.1899.peg.554       ---MHKPFKFTVALNKAVPLLYNALSSGEKLKTVELKWYRTSIEGKQENFFTTKLENASI
666.1897.peg.2311          GQRVHKPFKFTVALNKAVPLLYNALSSGEKLKTVELKWYRTSIEGKQENFFTTKLENASI
666.1907.peg.3336          GQRVHKPFKFTVALNKAVPLLYNALSSGEKLKTVELKWYRTSIEGKQENFFTTKLENASI
666.1905.peg.2607          GQRVHKPFKFTVALNKAVPLLYNALSSGEKLKSVELKWYRTSIEGKQENFFTTKLENASI
666.1901.peg.1846          GQRVHKPFKFTVALNKAVPLLYNALSSGEKLKSVELKWYRTSIEGKQENFFTTKLENASI
hcp2                       GQRVHKPFKFTVALNKAVPLLYNALSSGEKLKSVELKWYRTSIEGKQENFFTTKLENASI
                                      :********************:*********:*****************

fig|666.1893.peg.1367      VDIHCEMPHCQDPAKADFTQNLTVSLSYRKITWDHVNAGTSGSDDWRKPIEA
666.1906.peg.1334          VDIHCEMPHCQDPAKSDFTQNVTVSLSYRKITWDHVNAGTSGSDDWRKPIEA
fig|666.1899.peg.554       VDIHCEMPHCQDPAKSDFTQNVTVSLSYRKITWDHVNAGTSGSDDWRKPIEA
666.1897.peg.2311          VDIHCEMPHCQDPAKSDFTQNVTVSLSYRKITWDHVNAGTSGSDDWRKPIEA
666.1907.peg.3336          VDIHCEMPHCQDPAKSDFTQNVTVSLSYRKITWDHVNAGTSGSDDWRKPIEA
666.1905.peg.2607          VDIHCEMPHCQDPAKSDFTQNVTVSLSYRKITWDHVNAGTSGSDDWRKPIEA
666.1901.peg.1846          VDIHCEMPHCQDPAKSDFTQNVTVSLSYRKITWDHVNAGTSGSDDWRKPIEA
hcp2                       VDIHCEMPHCQDPAKSDFTQNVTVSLSYRKITWDHVNAGTSGSDDWRKPIEA
                           ***************:*****:******************************
