>BGT72_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
----------------------MNSNNSNTEF-----DGARAAQSRKKGFLGLAAAIVVA
GGSYALYWHFIGSRYISTDNAYAAAEIAEVTPVVGGIIAQVNVVDTEYVKQGDVL-VQLD
D--------------------------------------------TDARLALLQAEADLA
LAKRR-------------------------VRSYLANDEGLSAMVEAQEANEQRVKAQFK
AAQADF-------------------------------ERAKIDLSRREDLVRSGSVSGEE
LTNAKTGFAQAQANFNA-------------------------------------------
-------------AKAAMAQAQATKLSTIGSQKANAALTDN---TTVDSNPEVLLAKARY
EQAKIDLERTVIRAPISGVVAKRQVQVGRRVQVGMPLMTVVPT-TQIYVDANFKEVELRN
VKVGQPVTLTAD---------------LYGDEVTYH-GVVVGFSGGTGSAFSMIPAQNA-
-TGNWIKVVQRLPI----RIELDPKDLQAYPLQVGLSMVATIDTAGTTDPQTLVQYRAAK
VSEQG-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT72_aux1_vgrg
MATLAYTIHIDGLGDETLVVTSFEGQESLSNTVFQYAPCYGFRYEIALASRQPHLSAAQV
VDKSAELRMFRDGQLVQRVHGIVRAFSQGDIGHHYTLYSLTLVPALERLSLRHNSRIFQR
KTVPEILSVILQEMGINDYAFALERECEQREFCVQYRETDLDFLHRLAAEEGLVYCFTHE
AGKHTLLFS------DSSATLNKLAEPIPYNALAGGTQDTPYISGLTSRTETQVSDVELK
DYSFKKPNYSFLQRTQGEEMAYQQAIYSHFDAPGRYKDDLNGKAFSQVRLEYLRREAHTG
SGKSNQPLLRAGYKFTLQDHLNTAINRDWLLISVHHHGTQPQAMEEEGGSGATTYANQFT
VIPAHLNWQATPQPKPLVDGPMIATVVGPKGEEIFCDEYGRVKVHFHWDRYSNGDEQSSC
WVRVSQGWAGSQYGMITIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYPLPENKTK
TVLRSDTHQGEGFNELSFEDQAGKELIYLHAQKDMQVKVENSSHSRINYDQSVSIGHDEM
HVVANDRKLTVDGSQSQVTKGNYVSDTQGDKHESIGGDLARKIAGAIGVSADGDIT----
IKSGSKITLQVGGSFVVIDASGVA---IDGGTILIKSGGSPGS--------LALPSSAD-
-------------------VLEAAASAGS-------AFVANCPEMS--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT61_aux1_vgrg
MATLAYTIHIDGLGDETLVVTSFEGQESLSNTVFQYAPCYGFRYEIALASRQPHLSAAQV
VDKSAELRMFRDGQLVQRVHGIVRAFSQGDIGHHYTLYSLTLVPALERLSLRHNSRIFQR
KTVPEILSVILQEMGINDYAFALERECEQREFCVQYRETDLDFLHRLAAEEGLVYCFTHE
AGKHTLLFS------DSSATLNKLAEPIPYNALAGGTQDTPYISGLTSRTETQVSDVELK
DYSFKKPNYSFLQRTQGEEMAYQQAIYSHFDAPGRYKDDLNGKAFSQVRLEYLRREAHTG
SGKSNQPLLRAGYKFTLQDHLNTAINRDWLLISVHHHGTQPQAMEEEGGSGATTYANQFT
VIPAHLNWQATPQPKPLVDGPMIATVVGPKGEEIFCDEYGRVKVHFHWDRYSNGDEQSSC
WVRVSQGWAGSQYGMITIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYPLPENKTK
TVLRSDTHQGEGFNELSFEDQAGKELIYLHAQKDMQVKVENSSHSRINYDQSVSIGHDEM
HVVANDRKLTVDGSQSQVTKGNYVSDTQGDKHESIGGDLARKIAGAIGVSADGDIT----
IKSGSKITLQVGGSFVVIDASGVA---IDGGTILIKSGGSPGS--------LALPSSAD-
-------------------VLEAAASAGS-------AFVANCPEMS--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT71_aux2_vgrg
MATLAYTIHIDGLGDETLVVTSFEGQESLSNTVFQYAPCYGFRYEIALASRQPHLSAAQV
VDKSAELRMFRDGQLVQRVHGIVRAFSQGDIGHHYTLYSLTLVPALERLSLRHNSRIFQR
KTVPEILSVILQEMGINDYAFALERECEQREFCVQYRETDLDFLHRLAAEEGLVYCFTHE
AGKHTLLFS------DSSATLNKLAEPIPYNALAGGTQDTPYISGLTSRTETQVSDVELK
DYSFKKPNYSFLQRTQGEEMAYQQAIYSHFDAPGRYKDDLNGKAFSQVRLEYLRREAHTG
SGKSNQPLLRAGYKFTLQDHLNTAINRDWLLISVHHHGTQPQAMEEEGGSGATTYANQFT
VIPAHLNWQATPQPKPLVDGPMIATVVGPKGEEIFCDEYGRVKVHFHWDRYSNGDEQSSC
WVRVSQGWAGSQYGMITIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYPLPENKTK
TVLRSDTHQGEGFNELSFEDQAGKELIYLHAQKDMQVKVENSSHSRINYDQSVSIGHDEM
HVVANDRKLTVDGSQSQVTKGNYVSDTQGDKHESIGGDLARKIAGAIGVSADGDIT----
IKSGSKITLQVGGSFVVIDASGVA---IDGGTILIKSGGSPGS--------LALPSSAD-
-------------------VLEAAASAGS-------AFVANCPEMS--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BH2680_aux1_vgrg
MARLQFQLKVDGLEDESLVVRGFEGQESLSDSVWRSEPCYGFRYQVDLASALSNLAAEQF
VDQTAHLTILRDGQVVQQINGIVRQLSKGDTGHRHTFYSLTLVPELERLSLRSNSRIFQQ
QSVPEIISILLQEMGIEDYAFALKRECAQREFCVQYRETDLQFLHRIAAEEGLVYSHLHE
AQKHTLLFT------DSSDSQPKLAKPVPYNALAGGEINIPYVVDLQFKTTAQVSHTELK
DYSFKKPAYGFTQRTQGKDIAYQQPNYEHFDAPGRYKDDANGKAFSQIRLEYLRRDALLA
DAKSDEPLLLAGVRFDLQDHLDLAMNRDWLVVQANHQGTQPQALQEEGGSGATTYSNQLK
LIPAHITWRARPCAKPQVDGPMIATVVGPQGEEIYCDNFGRVKVHFPWDRYSSSNEKSSC
WVRVAQEWAGSQYGSMAIPRVGHEVIVSFLNGDPDQPIVTGRTYHATNTAPYALPDHKTK
TVLRTETHQGQGYNELSFEDQAGSEQILLHAQKDWDALIEHDHTEVIRHDQHLTVDNDRF
TRIQRNQHLTVEGEVRSKIALDSSHEVGASLQHKVGQRIAVEAGKEISLKSGAKIV----
VEAGAELTLKAGGSFVKVDAGGVH---LVGPAINLNAGGSAGSGSAYGGQLAAAPRMLA-
-QAKPVAELVQPDI----AASMQSGAARVIDVASLPTMMPSSANNTANDEPVAEEKTPER
ILKSDLLKPSDELEKLAKRQASAYRQGNHSDEVKLLQEALIKLGFDLGKAGADGDFGSKT
KTAIEQFQKSYQPSHQTHPSYSIGPVDGIVGKGTLLALDEALMDGGMYENDEMDLKWLIV
PKGQLTFDAEGNDVDSSTFFSRKVHVPNMRGSVIGNSGVTIGRGLDLGNPPSAASGQRPS
KINLKELFELANLNPKLSKWLLSVEGKTKDSALESLKNSGLSDEELTITRKQQYIMFNHV
YDYLEEKTRVLITKPDVKAAYGSVDWDGMPRNVKDVLVDITYRGDSYSKTRAWYVPTLVN
DRNSVDYSNFKKSLDYKNSIWDKVPLSRKRVRYE--------------------------
-----------------------------------HL-----------------------
-------------------------------------------------
>BGT8_aux1_vgrg
---------MEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYEVQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYQLTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGINDYAFALKRDGVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALVGGAIDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEDGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDHHLTVENDQF
TQIKHNQHLTVEWESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVALAPPQTISY----QALLQAEQANV-------PAVKVCPLAAQEATPAVNSITPPP
PPPIAPPMAPPQPIMNPQPTANAQPNLGRSTKATPDFPTHFPKSSIGIENELAGLVVAMP
ANSAQKFGYVKSAQGDALFMLTKDMNQGSYQRPPSLQDGKNYQNWQTHTVELVSYPCEMD
DKAAVETRKQAMLWLATHFTTHIDQSNHQPLAPIQSEDGRFVIEITNAKHVIAAGNGISA
ESQGQTITMTPSGQQATVGVAAKGFGTSATPELRLLESAPWYQKSLKSQFASLTSAENLD
DKELAANVFAYLTSIYLKTAELAKKFGIYINEWDPMSSKLLQMRMD--------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT66_aux1_vgrg
---------------------------------------------MQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYQLTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGINDYAFALKRDGVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALVGGAIDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEDGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDHHLTVENDQF
TQIKHNQHLTVEWESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVALAPPQTISY----QALLQAEQANV-------PAVKVCPLAAQEATPAVNSITPPP
PPPIAPPMAPPQPIMNPQPTANAQPNLGRSTKATPDFPTHFPKSSIGIENELAGLVVAMP
ANSAQKFGYVKSAQGDALFMLTKDMNQGSYQRPPSLQDGKNYQNWQTHTVELVSYPCEMD
DKAAVETRKQAMLWLATHFTTHIDQSNHQPLAPIQSEDGRFVIEITNAKHVIAAGNGISA
ESQGQTITMTPSGQQATVGVAAKGFGTSATPELRLLESAPWYQKSLKSQFASLTSAENLD
DKELAANVFAYLTSIYLKTAELAKKFGIYINEWDPMSSKLLQMRMD--------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT62_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------MGP---------------------------------------
------------------------------------------------------------
------------------------------------------------HVEQITPNAN--
----------------------------GLTDPKVKNAW------EILPRTKPSKI----
VEILSKSDAKAVMKHIKPQLQSRYSESLSKNVFQYFQDGGEVAGHGINNATVGDKHSPE-
-LAIL------FEF----RTVPNELQSYL-------PKTESTTKSEVKL-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------LDQFDPMKRKTVIQQVESLVQNS
GDAFDKWYQSYRDSMNQPPVKNAKKIASANQKAQWVKEHNPQEWQRIIA
>BGT60_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------MGP---------------------------------------
------------------------------------------------------------
------------------------------------------------HVEQITPNAN--
----------------------------GLTDPKVKNAW------EILPRTKPSKI----
VEILSKSDAKAVMKHIKPQLQSRYSESLSKNVFQYFQDGGEVAGHGINNATVGDKHSPE-
-LAIL------FEF----RTVPNELQSYL-------PKTESTTKSEVKL-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------LDQFDPMKRKTVIQQVESLVQNS
GDAFDKWYQSYRDSMNQPPVKNAKKIASANQKAQWVKEHNPQEWQRIIA
>BH2681_aux1_vgrg
MATLAYSIEVEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQVQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYELTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGINDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDANGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYNNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKAGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAAQEAMPAVNSIAPPP
PPPIAPPMAPPQPIMNPQPTANAQPNLGRSTKATPDFPTHFPKSSIGIENELAGLVVAMP
ANSAQKFGYVKSAQGDALFMLTKDMNQGSYQRPPSLQDGKNYQNWQTHTVELVSYPCEMD
DKAAVETRKQAMLWLATHFTTHIDQSNHQPLAPIQSEDGRFVIEITNAKHVIAAGNGISA
ESQGQTITMTPSGQQATVGVAAKGFGTSATPELRLLESAPWYQKSLKSQFASLTSAENLD
DKELAANVFAYLTSIYLKTAELAKKFGIYINEWDPMSEQITPNANGLTDPKVKNAWEILP
RTKPSKIVEILSKSDAKAVMKHIKPQLQSRYSESLSKNVFQYFQDGGEVAGHGINNATVG
DKHSPELAVLFEFRTVPNELQSYLPKTESTTKSEVKLLDQFDPMKRKTVIQQVESLVQNS
GDAFDKWYQSYRDSMNQPPVKNAKKIASANQKAQWVKEHNPQEWQRIIA
>BH1545_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDHHLTVENDQF
TQIKHNQHLTVEWESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVALAPPQTISY----QALLQAEQANV-------PAVKVCPLAAQEATPAVNSITPPP
PPPIAPPMAPPQPIMNPQPTANAQPNLGRSTKATPDFPTHFPKSSIGIENELAGLVVAMP
ANSAQKFGYVKSAQGDALFMLTKDMNQGSYQRPPSLQDGKNYQNWQTHTVELVSYPCEMD
DKAAVETRKQAMLWLATHFTTHIDQSNHQPLAPIQSEDGRFVIEITNAKHVIAAGNGISA
ESQGQTITMTPSGQQATVGVAAKGFGTSATPELRLLESAPWYQKSLKSQFASLTSAENLD
DKELAANVFAYLTSIYLKTAELAKKFGIYINEWDPMSEQITPNANGLTDPKVKNAWEILP
RTKPSKIVEILSKSDAKAVMKHIKPQLQSRYSESLSKNVFQYFQDGGEVAGHGINNATVG
DKHSPELAILFEFRTVPNELQSYLPKTESTTKSEVKLLDQFDPMKRKTVIQQVESLVQNS
GDAFDKWYQSYRDSMNQPPVKNAKKIASANQKAQWVKEHNPQEWQRIIA
>SW491_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDHHLTVENDQF
TQIKHNQHLTVEWESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVALAPPQTISY----QALLQAEQANV-------PAVKVCPLAAQEATPAVNSITPPP
PPPIAPPMAPPQPIMNPQPTANAQPNLGRSTKATPDFPTHFPKSSIGIENELAGLVVAMP
ANSAQKFGYVKSAQGDALFMLTKDMNQGSYQRPPSLQDGKNYQNWQTHTVELVSYPCEMD
DKAAVETRKQAMLWLATHFTTHIDQSNHQPLAPIQSEDGRFVIEITNAKHVIAAGNGISA
ESQGQTITMTPSGQQATVGVAAKGFGTSATPELRLLESAPWYQKSLKSQFASLTSAENLD
DKELAANVFAYLTSIYLKTAELAKKFGIYINEWDPMSEQITPNANGLTDPKVKNAWEILP
RTKPSKIVEILSKSDAKAVMKHIKPQLQSRYSESLSKNVFQYFQDGGEVAGHGINNATVG
DKHSPELAILFEFRTVPNELQSYLPKTESTTKSEVKLLDQFDPMKRKTVIQQVESLVQNS
GDAFDKWYQSYRDSMNQPPVKNAKKIASANQKAQWVKEHNPQEWQRIIA
>BGT11_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---MSQGWAGSQHGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEIAVKAGGSFVKVDPAGVH---LSGALVNLNSGGCAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAAQEATPAVNSITPPP
PPPIAPPMAPPQPIMNPQPTANAQPNLGRSTKATPDFPTHFPKSSIGIENELAGLVVAMP
ANSAQKFGYVKSAQGDALFMLTKDMNQGSYQRPPSLQDGKNYQNWQTHTVELVSYPCEMD
DKAAVETRKQAMLWLATHFTTHIDQSNHQPLAPIQSEDGRFVIEITNAKHVIAAGNGISA
ESQGQTITMTPSGQQATVGVAAKGFGTSATPELRLLESAPWYQKSLKSQFASLTSAENLD
DKELAANVFAYLTSIYLKTAELAKKFGIYINEWDPMSEQITPNANGLTDPKVKNAWEILP
RTKPSKIVEILSKSDAKAVMKHIKPQLQSRYSESLSKNVFQYFQDGGEVAGHGINNATVG
DKHSPELAILFEFRTVPNELQSYLPKTESTTKSEVKLLDQFDPMKRKTVIQQVESLVQNS
GDAFDKWYQSYRDSMNQPPVKNAKKIASANQKAQWVKEHNPQEWQRIIA
>BGT64_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPENKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDHHLTVENDQF
TQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKAGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLD-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGASS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT7_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPENKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDHHLTVENDQF
TQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKAGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLD-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGASS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT46_aux1_vgrg
------------------------------------------------------------
------------------------------------------MPALERLSLRHNSRIFQK
QTVPEILSILLQEMGINDYAFALKRDGVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELGYQQTRYQHFDAPGRYKDDVNGEAFSQIRLDYLRRNAHTA
AGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQAKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNSNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKGNQHLTVEGESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QVLLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT49_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MQGTELGYQQTRYQHFDAPGRYKDDVNGEAFSQIRLDYLRRHAHTA
AGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQAKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNSNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKGNQHLTVEGESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QVLLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>EB6491_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT63_aux1_vgrg
MATLAYSIEVEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQVQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYELTLVPALERLSLRHNSRIFQK
QTVPEIISILLQEMGIHDYAFALKRDGVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYRNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKAGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT65_aux1_vgrg
MATLAYSIEVEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQVQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYELTLVPALERLSLRHNSRIFQK
QTVPEIISILLQEMGIHDYAFALKRDGVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYRNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKAGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT68_aux1_vgrg
---------------------------------------------MQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYELTLVPALERLSLRHNSRIFQK
QTVPEIISILLQEMGIHDYAFALKRDGVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYRNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKAGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT69_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---MSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKAGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT70_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKAGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Colwell_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---MSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYSLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT61_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MEGESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT41_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------MNRDWVVVSINHQGEQPQALQEEGGSGATTYNNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESREAVTGEQVLSIEGSLHVKTGKVWVNEAGTEIHVKAGQKVV----
IEAGSEITVKAGGSFVKVDPAGVH---LSGALVNLNSGGSAGSGSGFGGAMPALPGGLE-
-PAVTLAPPQTISY----QALLQAEQANV-------PAVKVCPLAGANS-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT71_aux1_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------MNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQSQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYSLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKVAELPFGLE-
----ALSAPDEIDFILPTASLIQQVIADV---KIEMPITQVCQKRSDGSCPLSDCPCGNN
K-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT61_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------MNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQSQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYSLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
SQIKHNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKVAELPFGLE-
----ALSAPDEIDFILPTASLIQQVIADV---KIEMPITQVCQKRSDGSCPLSDCPCGNN
K-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT65_aux2_vgrg
MATLAYSIEVEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQVQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYELTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGINDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPILRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYSNQFS
LILGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT68_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>SW491_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT66_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKVGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT62_aux2_vgrg
---------MEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQMQLASRVSNLTADQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYQLTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGIHDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYNNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKVGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT60_aux2_vgrg
---------MEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQMQLASRVSNLTADQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYQLTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGIHDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYNNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKVGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT42_aux2_vgrg
---------MEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQMQLASRVSNLTADQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYQLTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGIHDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYNNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKVGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT8_aux2_vgrg
---------MEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQMQLASRVSNLTADQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYQLTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGIHDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYNNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKVGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BH1545_aux2_vgrg
---------------------------------------------MQLASRVSNLTADQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYQLTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGIHDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYNNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDCSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT46_aux2_vgrg
------------------------------------------------------------
------------------------------------------MPALERLSLRHNSRIFQK
QTVPEILSILLQEMGINDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYHTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEDGGSGATTYSNQFS
LIPGHLHWRAEPQAKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT49_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEDGGSGATTYSNQFS
LIPGHLHWRAEPQAKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BH2680_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------MSINHQGEQPQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVEFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TEIKHNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT41_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------MNRDWVVVSINHQGEQPQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFVAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TEIKRNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGNKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGPGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BH2681_aux2_vgrg
MATLAYSIEVEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYEVQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYELTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGIHDYAFALKRDCVQREFCVQYRESDMDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPENKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TEIKRNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGLGYGGKMAELPQGVD-
-KAKT---PQEIEL----AAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT63_aux2_vgrg
MATLAYSIEVEGLEDETLVVRGFHGQESLSNSVFLGQACYGFRYQVQLASRVSNLTAEQM
VDKRAELKLYRNSQLVQRVHGIVRAFSQGDIGHHHTFYELTLVPALERLSLRHNSRIFQK
QTVPEILSILLQEMGINDYAFALKRDCVQREFCVQYRESDIDFLHRLAAEEGLVYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYSNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TEIKRNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGNKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKVAELPQGVD-
-KAQT---PQEIEL----TAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT69_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---MSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TEIKRNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGNKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKVAELPQGVD-
-KAQT---PQEIEL----TAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT70_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDQHLTVENDQF
TEIKRNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGNKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKVAELPQGVD-
-KAQT---PQEIEL----TAVTPTQQSMS-------PLLKARQIEALKGPAPVCEVCEEA
KGN---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT42_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPEHKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTAVIRHDQHLTVENDQF
TEIKRNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGNKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGPGYGGKMAELPHQMKA
TPTAPNPLPLQLSA----PTMATLAMANV-------PLAKMCQRQSDGSCPRGDCPCERG
AS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>EB6491_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTAVIRHDQHLTVENDQF
TEIKRNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGNKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGGFIKVDAGGVH---VVGSAINLNSGGSAGSGPGYGGKMAELPHQMKA
TPTAPNPLPLQLSA----PTMATLAMANV-------PLAKMCQRQSDGSCPRGDCPCERG
AS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Colwell_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MIENDHTTVIRHDHHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDSSSEICGSLQQKIGSKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPHQMKA
TPAAPNPLPLQLSA----PTMATLAMANV-------PLAKMCQRQSDGSCPRGDCPCERG
AS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT64_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYRNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPENKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGNKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPHQMKA
TPAAPNPLPLQLSA----PTMATLAMANV-------PLAKMCQRQSDGSCPRGDCPCERG
AS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>BGT7_aux2_vgrg
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MYSFVHE
AGKHTLYFS------DASDSLSKLPEPIPYNALAGGTMDTPYIHGLTYRTQAEVSEVQLK
DYSFKKPAYSFLQTVQGTELDYQQTRYQHFDAPGRYKDDVNGAAFSQIRLDYLRRHAHTA
TGQSNEPLLRAGYKFDLQEHLDPAMNRDWVVVSINHQGEQPQALQEEGGSGATTYRNQFS
LIPGHLHWRAEPQPKPQVDGPMIATVVGPEGEEIFCDEHGRVKIHFPWDRYSNGNEQSSC
WVRVSQGWAGSQYGFIAIPRIGHEVIVSFLNGDPDQPIITGRTYHATNTPPYTLPENKTK
TVLRTETHQGEGFNELSFEDQAGKEQIYLHAQKDFDGLIENDHTTVIRHDQHLTVENDQF
TQIKHNQHLTVEGESRTLVKLDSSSEIGGSLQQKIGNKAIYDAGTEVHLKAGNKLV----
LEAGNELTIKAGGSFIKVDAGGVH---VVGSAINLNSGGSAGSGSGYGGKMAELPHQMKA
TPAAPNPLPLQLSA----PTMATLAMANV-------PLAKMCQRQSDGSCPRGDCPCERG
AS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
